# Generated by Django 3.0.4 on 2020-03-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={"verbose_name": "UserInfo", "verbose_name_plural": "UserInfo"},
        ),
    ]
