# Generated by Django 3.0.4 on 2020-03-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("auth", models.CharField(blank=True, max_length=50, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("tag", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("txt", models.TextField()),
                ("delete", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Note", "verbose_name_plural": "Notes",},
        ),
        migrations.CreateModel(
            name="NoteHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txt", models.TextField()),
                ("version", models.IntegerField()),
                ("delete", models.BooleanField(default=False)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="note.Note"
                    ),
                ),
            ],
            options={
                "verbose_name": "NoteHistory",
                "verbose_name_plural": "NoteHistorys",
            },
        ),
    ]
