# Generated by Django 3.0.4 on 2020-03-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='data_type',
            field=models.CharField(choices=[('note', 'Note'), ('article', 'Article'), ('sys', 'Sys')], default='note', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
